config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  root to: "homes#show"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do
      post "like" => "user_likes#create", as: "like"
      delete "unlike" => "user_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
    end
  end

  resources :groups, only: [:new, :create, :show, :index] do
    member do
      post "like" => "group_likes#create", as: "like"
      delete "unlike" => "group_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end

  resources :galleries do
    member do
      post "like" => "gallery_likes#create", as: "like"
      delete "unlike" => "gallery_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
    end
    resources :images, except: [:index] do
      member do
        post "like" => "image_likes#create", as: "like"
        delete "unlike" => "image_likes#destroy", as: "unlike"
        post "hate" => "hates#create", as: "hate"
        delete "unhate" => "hates#destroy", as: "unhate"
      end
      resources :comments, only: [:new, :create] do
        member do
          post "like" => "comment_likes#create", as: "like"
          delete "like" => "comment_likes#destroy", as: "unlike"
          post "hate" => "hates#create", as: "hate"
          delete "unhate" => "hates#destroy", as: "unhate"
        end
      end
    end
  end

  resources :tags, only: [:show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
  has_many :likes, as: :content, dependent: :destroy
  has_many :hates, as: :hateable, dependent: :destroy

  default_scope { order(created_at: :asc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    image = Image.find(params[:image_id])
    image.comments.create(comment_params)
    redirect_to [image.gallery, image]
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user: current_user)
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <strong><%= comment.user.email %></strong>
  <div>
    Likes: <%= comment.likes.count %>
    <% if current_user.liked?(comment) %>
      <%= link_to "Like", like_gallery_image_comment_path(@gallery, @image, comment), method: :post %>
    <% else %>
      <%= link_to "Unlike", unlike_gallery_image_comment_path(@gallery, @image, comment), method: :delete %>
    <% end %>
  </div>
  <div>
    Hates: <%= comment.hates.count %>
    <% if current_user.hated?(comment) %>
      <%= link_to "Hate", hate_gallery_image_comment_path(@gallery, @image, comment), method: :post %>
    <% else %>
      <%= link_to "Unhate", unhate_gallery_image_comment_path(@gallery, @image, comment), method: :delete %>
    <% end %>
  </div>
  <p><%= time_ago_in_words(comment.created_at) %></p>
  <p><%= comment.content %></p>
</div>