config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  root to: "homes#show"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do
      post "like" => "user_likes#create", as: "like"
      delete "unlike" => "user_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
    end
  end

  resources :groups, only: [:new, :create, :show, :index] do
    member do
      post "like" => "group_likes#create", as: "like"
      delete "unlike" => "group_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end

  resources :galleries do
    member do
      post "like" => "gallery_likes#create", as: "like"
      delete "unlike" => "gallery_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
    end
    resources :images, except: [:index] do
      member do
        post "like" => "image_likes#create", as: "like"
        delete "unlike" => "image_likes#destroy", as: "unlike"
        post "hate" => "hates#create", as: "hate"
        delete "unhate" => "hates#destroy", as: "unhate"
      end
      resources :comments, only: [:new, :create] do
        member do
          post "like" => "comment_likes#create", as: "like"
          delete "like" => "comment_likes#destroy", as: "unlike"
          post "hate" => "hates#create", as: "hate"
          delete "unhate" => "hates#destroy", as: "unhate"
        end
      end
    end
  end

  resources :tags, only: [:show]
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_memberships
  has_many :users, through: :group_memberships
  has_and_belongs_to_many :images
  has_many :likes, as: :content, dependent: :destroy
  has_many :hates, as: :hateable, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login, except: [:index, :show]
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.users << current_user
    if group.save
      redirect_to group
    else
      render :new
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/views/groups/_group.html.erb
<%= link_to group.name, group %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<%= link_to "New Group", new_group_path %><br/>

<% @groups.each do |group| %>
  <%= link_to group.name, group_path(group) %>
<% end %>

app/views/groups/new.html.erb
<%= form_for @group do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.submit "Create Group" %>
  </div>
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<div>
  Likes: <%= @group.likes.count %>
  <% if current_user.liked?(@group) %>
    <%= link_to "Like", like_group_path(@group), method: :post %>
  <% else %>
      <%= link_to "Unlike", unlike_group_path(@group), method: :delete %>
  <% end %>
</div>
<div>
  Hates: <%= @group.hates.count %>
  <% if current_user.hated?(@group) %>
    <%= link_to "Hate", hate_group_path(@group), method: :post %>
  <% else %>
      <%= link_to "Unhate", unhate_group_path(@group), method: :delete %>
  <% end %>
</div>

<div>
<% if current_user.member?(@group) %>
  <%= link_to "Leave Group", leave_group_path(@group), method: :delete, data: { confirm: "Are You Sure?" } %>
<% else %>
  <%= link_to "Join Group", join_group_path(@group), method: :post %>
<% end %>
</div>
<ul>
  <% @group.images.each do |image| %>
    <li><%= render image  %></li>
  <% end %>
</ul>