config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  root to: "homes#show"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do
      post "like" => "user_likes#create", as: "like"
      delete "unlike" => "user_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
    end
  end

  resources :groups, only: [:new, :create, :show, :index] do
    member do
      post "like" => "group_likes#create", as: "like"
      delete "unlike" => "group_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end

  resources :galleries do
    member do
      post "like" => "gallery_likes#create", as: "like"
      delete "unlike" => "gallery_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
    end
    resources :images, except: [:index] do
      member do
        post "like" => "image_likes#create", as: "like"
        delete "unlike" => "image_likes#destroy", as: "unlike"
        post "hate" => "hates#create", as: "hate"
        delete "unhate" => "hates#destroy", as: "unhate"
      end
      resources :comments, only: [:new, :create] do
        member do
          post "like" => "comment_likes#create", as: "like"
          delete "like" => "comment_likes#destroy", as: "unlike"
          post "hate" => "hates#create", as: "hate"
          delete "unhate" => "hates#destroy", as: "unhate"
        end
      end
    end
  end

  resources :tags, only: [:show]
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images, dependent: :destroy
  has_many :likes, as: :content, dependent: :destroy
  has_many :hates, as: :hateable, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :require_login

  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def show
    @gallery = find_gallery
    @images = @gallery.images
  end

  def create
    final_params = gallery_params.merge(user_id: current_user.id)
    @gallery = Gallery.new(final_params)
    if @gallery.save
      redirect_to galleries_path
    else
      render :new
    end
  end

  def edit
    @gallery = find_gallery
  end

  def update
    @gallery = find_gallery
    if @gallery.update(gallery_params)
      redirect_to gallery_path(@gallery.id)
    else
      render :edit
    end
  end

  def destroy
    gallery = find_gallery
    gallery.destroy
    redirect_to "/galleries"
  end

  private

  def find_gallery
    Gallery.find(params[:id])
  end

  def gallery_params # strong_params
    params.require(:gallery).permit(:name, :description)
  end
end

app/views/galleries/_form.html.erb
<%= render "errors", object: form.object %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div>
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

app/views/galleries/_gallery.html.erb
<%= link_to gallery.name, gallery %>

app/views/galleries/edit.html.erb
<h1>Edit <%= @gallery.name %></h1>
<%= form_for @gallery do |form| %>
  <%= render form %>
  <%= form.submit "Edit Gallery" %>
<% end %>

app/views/galleries/index.html.erb
<%= link_to "New Gallery", "/galleries/new" %>
<% @galleries.each do |gallery| %>
  <%= render gallery%>
<% end %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>
<%= form_for @gallery do |form| %>
  <%= render form %>
  <%= form.submit "Create Gallery" %>
<% end %>

app/views/galleries/show.html.erb
<h1><%= @gallery.name %></h1>
<div>
Likes: <%= @gallery.likes.count %>
<% if current_user.liked?(@gallery) %>
  <%= link_to "Like", like_gallery_path(@gallery), method: :post %>
<% else %>
    <%= link_to "Unlike", unlike_gallery_path(@gallery), method: :delete %>
<% end %>
</div>
<div>
Hates: <%= @gallery.hates.count %>
<% if current_user.hated?(@gallery) %>
  <%= link_to "Hate", hate_gallery_path(@gallery), method: :post %>
<% else %>
    <%= link_to "Unhate", unhate_gallery_path(@gallery), method: :delete %>
<% end %>
</div>
<p><%= @gallery.description.capitalize %></p>

<nav>
<%= link_to "New Image", new_gallery_image_path(@gallery) %>
<%= link_to "Edit", edit_gallery_path(@gallery) %>
<%= link_to "Destroy", @gallery, method: :delete, data: { confirm: "Are you sure?" } %>
</nav>

<ul>
  <% @images.each do |image| %>
    <li><%= render image %>
<%= link_to "Destroy Image", [@gallery, image], method: :delete, data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>