config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  root to: "homes#show"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do
      post "like" => "user_likes#create", as: "like"
      delete "unlike" => "user_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
    end
  end

  resources :groups, only: [:new, :create, :show, :index] do
    member do
      post "like" => "group_likes#create", as: "like"
      delete "unlike" => "group_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end

  resources :galleries do
    member do
      post "like" => "gallery_likes#create", as: "like"
      delete "unlike" => "gallery_likes#destroy", as: "unlike"
      post "hate" => "hates#create", as: "hate"
      delete "unhate" => "hates#destroy", as: "unhate"
    end
    resources :images, except: [:index] do
      member do
        post "like" => "image_likes#create", as: "like"
        delete "unlike" => "image_likes#destroy", as: "unlike"
        post "hate" => "hates#create", as: "hate"
        delete "unhate" => "hates#destroy", as: "unhate"
      end
      resources :comments, only: [:new, :create] do
        member do
          post "like" => "comment_likes#create", as: "like"
          delete "like" => "comment_likes#destroy", as: "unlike"
          post "hate" => "hates#create", as: "hate"
          delete "unhate" => "hates#destroy", as: "unhate"
        end
      end
    end
  end

  resources :tags, only: [:show]
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery

  has_and_belongs_to_many :groups

  has_many :comments
  has_many :likes, as: :content, dependent: :destroy
  has_many :hates, as: :hateable, dependent: :destroy

  acts_as_taggable

  validates :name, presence: true
  validates :description, presence: true
  validates :url, presence: true

  def liked_count
    Like.where(content_id: self.id).size
  end

  def hated_count
    Hate.where(hateable_id: self.id).size
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
    @gallery = find_gallery
    @image = find_image_in(@gallery)
    @comment = Comment.new
  end

  def new
    @gallery = find_gallery
    @image = Image.new
  end

  def create
    gallery = find_gallery

    @image = gallery.images.new(image_params)
    if @image.save
      redirect_to gallery
    else
      render :new
    end
  end

  def edit
    @gallery = find_gallery
    @image = find_image_in(@gallery)
  end

  def update
    @gallery = find_gallery

    @image = find_image_in(@gallery)
    if @image.update(image_params)
      redirect_to [@gallery, @image]
    else
      render :edit
    end
  end

  def destroy
    gallery = find_gallery
    @image = find_image_in(gallery)
    @image.destroy

    redirect_to gallery_path(params[:gallery_id])
  end

  private

  def find_gallery
    Gallery.find(params[:gallery_id])
  end

  def find_image_in(gallery)
    gallery.images.find(params[:id])
  end

  def image_params # strong_params
    params.
      require(:image).
      permit(:name, :description, :url, :tag_list, group_ids: [])
  end
end

app/views/images/_form.html.erb
<%= render "errors", object: form.object %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div>
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>
<div>
  <%= form.label :url %>
  <%= form.text_field :url %>
</div>
<div>
  <%= form.collection_check_boxes :group_ids, current_user.groups, :id, :name %>
</div>
<div>
  <%= form.label :tag_list %>
  <%= form.text_field :tag_list  %>
</div>

app/views/images/_image.html.erb
<%= link_to [image.gallery, image] do -%>
  <%= image_tag image.url, width: 200 -%>
<% end %>

app/views/images/edit.html.erb
<h1>Edit Image in <%= @gallery.name %></h1>
<%= form_for [@gallery, @image] do |form| %>
  <%= render form %>
<%= form.submit %>
<% end %>

app/views/images/new.html.erb
<h1>New Image in <%= @gallery.name %></h1>
<%= form_for [@gallery, @image] do |form| %>
  <%= render form  %>
  <%= form.submit %>
<% end %>

app/views/images/show.html.erb
<h3><%= @image.name %></h3>
<%= image_tag @image.url, width: 300 %>
<%= link_to "Edit Image", edit_gallery_image_path(@image.gallery_id, @image.id) %>
<%= link_to "Delete Image", [@image.gallery, @image], method: :delete, data: { confirm: "Are you sure?" } %>

<div>
  <%= pluralize(@image.tags.count, "Tag") %><br/>
  <% @image.tags.each do |tag| %>
    <%= link_to tag, tag_path(tag)  %>
  <% end %>
</div>
<br/>
<%= pluralize(@image.liked_count, "Like") %>

<% if current_user.liked?(@image) %>
  <%= link_to "Like", like_gallery_image_path(@gallery, @image), method: :post %>
<% else %>
  <%= link_to "Unlike", unlike_gallery_image_path(@gallery, @image), method: :delete %>
<% end %>
<br/>

<%= pluralize(@image.hated_count, "Hate") %>


<% if current_user.hated?(@image) %>
<%= link_to "Hate", hate_gallery_image_path(@gallery, @image), method: :post %>
<% else %>
<%= link_to "Unhate", unhate_gallery_image_path(@gallery, @image), method: :delete %>
<% end %>
<%= render @image.comments %>

<%= form_for [@gallery, @image, @comment] do |form| %>
  <%= form.text_area :content %>
  <%= form.submit "Post" %>
<% end %>